CREATE TABLE IF NOT EXISTS "Sources" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Sources" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "FirstName" text,
    "LastName" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Prospects" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlayerName" text NOT NULL,
    "Team" text NOT NULL,
    "Position" text NOT NULL,
    "Age" integer NOT NULL,
    "ETA" text,
    "Rank" integer NOT NULL,
    "SourceId" integer NOT NULL,
    CONSTRAINT "PK_Prospects" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Prospects_Sources_SourceId" FOREIGN KEY ("SourceId")
        REFERENCES "Sources" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Sources_Name" ON "Sources" ("Name");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users" ("Email");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Prospects_SourceId_Rank" ON "Prospects" ("SourceId", "Rank");
