CREATE TABLE IF NOT EXISTS "Rankings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Rank" integer NOT NULL,
    "PlayerName" varchar(255) NOT NULL,
    "Team" varchar(255) NOT NULL,
    "Position" varchar(255) NOT NULL,
    "Age" integer,
    "ETA" varchar(255),
    "Score" integer,
    "Volatility" varchar(255) DEFAULT '',
    "Consensus" integer,
    CONSTRAINT "PK_Rankings" PRIMARY KEY ("Id")
);