ALTER TABLE "Rankings"
    ALTER COLUMN "Score" TYPE double precision;

ALTER TABLE "Rankings"
    ADD COLUMN IF NOT EXISTS "Median" double precision,
    ADD COLUMN IF NOT EXISTS "Sd" double precision,
    ADD COLUMN IF NOT EXISTS "Tier" integer NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS "SourceCount" integer NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS "Sources" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Sources" PRIMARY KEY ("Id")
);
